-- 1. Create blocked_users table
CREATE TABLE IF NOT EXISTS blocked_users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    blocker_id UUID REFERENCES profiles(id) NOT NULL,
    blocked_id UUID REFERENCES profiles(id) NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(blocker_id, blocked_id)
);

-- RLS for blocked_users
ALTER TABLE blocked_users ENABLE ROW LEVEL SECURITY;

-- Allow users to view their own blocks
DROP POLICY IF EXISTS "Users can view their own blocks" ON blocked_users;
CREATE POLICY "Users can view their own blocks"
ON blocked_users FOR SELECT
USING (auth.uid() IN (
    SELECT user_id FROM profiles WHERE id = blocker_id OR id = blocked_id
));

-- Allow users to insert blocks (block someone)
DROP POLICY IF EXISTS "Users can block others" ON blocked_users;
CREATE POLICY "Users can block others"
ON blocked_users FOR INSERT
WITH CHECK (
    blocker_id IN (SELECT id FROM profiles WHERE user_id = auth.uid())
);

-- Allow users to delete their own blocks (unblock)
DROP POLICY IF EXISTS "Users can unblock" ON blocked_users;
CREATE POLICY "Users can unblock"
ON blocked_users FOR DELETE
USING (
    blocker_id IN (SELECT id FROM profiles WHERE user_id = auth.uid())
);


-- 2. Create user_reports table
CREATE TABLE IF NOT EXISTS user_reports (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reporter_id UUID REFERENCES profiles(id) NOT NULL,
    reported_id UUID REFERENCES profiles(id) NOT NULL,
    reason TEXT NOT NULL,
    details TEXT,
    status TEXT DEFAULT 'pending', -- pending, reviewed, dismissed, acted
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- RLS for user_reports
ALTER TABLE user_reports ENABLE ROW LEVEL SECURITY;

-- Allow users to insert reports
DROP POLICY IF EXISTS "Users can submit reports" ON user_reports;
CREATE POLICY "Users can submit reports"
ON user_reports FOR INSERT
WITH CHECK (
    reporter_id IN (SELECT id FROM profiles WHERE user_id = auth.uid())
);

-- Allow users to view their own reports
DROP POLICY IF EXISTS "Users can view their own reports" ON user_reports;
CREATE POLICY "Users can view their own reports"
ON user_reports FOR SELECT
USING (
    reporter_id IN (SELECT id FROM profiles WHERE user_id = auth.uid())
);
